services:
  - type: web
    name: theblackhole
    env: node
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
    staticPublishPath: ./client/build

  - type: web
    name: the-black-hole-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: the-black-hole
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://the-black-hole-api.onrender.com 